url: https://wslh-data.github.io
baseurl: /dataportal

# Site settings
title: Wisconsin State Laboratory of Hygiene DataPortal
organization: Wisconsin State Laboratory of Hygiene
logo: wslh-logo.png
logo_alt: Wisconsin State Laboratory of Hygiene DataPortal
email: 
description: "The Wisconsin State Laboratory of Hygiene (WSLH) is the state’s public and environmental health laboratory. As part of the University of Wisconsin-Madison, the WSLH is committed to exploring new ideas which benefit the state, the nation and the world."

collections:
  dashboards:
    output: true
    permalink: /:slug
    sort_by: dashboard-id

# Team names, titles and social links
#people:
#- name: Kay Garland
#  pic: 1
#  position: Lead Designer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #
#
#- name: Larry Parker
#  pic: 2
#  position: Lead Marketer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: linkedin
#      url: #
#
#- name: Diana Petersen
#  pic: 3
#  position: Lead Developer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/wslh-data
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll


# Postal address (add as many lines as necessary)
address:
  - line: 'Attn: Customer Service'
  - line: Wisconsin State Laboratory of Hygiene
  - line: 2601 Agriculture Drive, PO Box 7996
  - line: Madison, WI 53707-7996

# Build settings
markdown: kramdown
permalink: pretty